### ISSUE TITLE
Word similarity using phrase bert

### ISSUE THREAD

**Issue by saurabh0512** [sf-wa-326/phrase-bert-topic-model#6]
Hi,
I have 2 part question regarding my problem where I have to find similar terms in domain specific dataset.
1. How is Phrase Bert getting embeddings of vectors without context as is needed by BERT?
2. Are clustering algorithms suitable to get all similar terms to specified terms?

**Comment by sf-wa-326** [comment]
Hey yes so for question 1, we simply forward pass the input phrase as if it is a sentence to get the output vectors, and then these vectors are mean-pooled to form a single vector, as a representation for the given phrase. For question 2, yes I think so. And you may try using either the dot product or cosine similarity as the distance metrics for clustering.
